// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var header = ReasonReact.statelessComponent("Header");

function make(title, _children) {
  return /* record */[
          /* debugName */header[/* debugName */0],
          /* reactClassInternal */header[/* reactClassInternal */1],
          /* handedOffState */header[/* handedOffState */2],
          /* willReceiveProps */header[/* willReceiveProps */3],
          /* didMount */header[/* didMount */4],
          /* didUpdate */header[/* didUpdate */5],
          /* willUnmount */header[/* willUnmount */6],
          /* willUpdate */header[/* willUpdate */7],
          /* shouldUpdate */header[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", undefined, title);
            }),
          /* initialState */header[/* initialState */10],
          /* retainedProps */header[/* retainedProps */11],
          /* reducer */header[/* reducer */12],
          /* jsElementWrapped */header[/* jsElementWrapped */13]
        ];
}

exports.header = header;
exports.make = make;
/* header Not a pure module */
