// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Panel$ReactTemplate = require("./Panel.bs.js");
var Header$ReactTemplate = require("./Header.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Panel$ReactTemplate.make("apples", /* array */[])), "panel");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Header$ReactTemplate.make("Move along", /* array */[])), "header");

/*  Not a pure module */
