// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var panel = ReasonReact.statelessComponent("Panel");

function make(name, _children) {
  return /* record */[
          /* debugName */panel[/* debugName */0],
          /* reactClassInternal */panel[/* reactClassInternal */1],
          /* handedOffState */panel[/* handedOffState */2],
          /* willReceiveProps */panel[/* willReceiveProps */3],
          /* didMount */panel[/* didMount */4],
          /* didUpdate */panel[/* didUpdate */5],
          /* willUnmount */panel[/* willUnmount */6],
          /* willUpdate */panel[/* willUpdate */7],
          /* shouldUpdate */panel[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", undefined, name);
            }),
          /* initialState */panel[/* initialState */10],
          /* retainedProps */panel[/* retainedProps */11],
          /* reducer */panel[/* reducer */12],
          /* jsElementWrapped */panel[/* jsElementWrapped */13]
        ];
}

exports.panel = panel;
exports.make = make;
/* panel Not a pure module */
